/* cards.js — talia startowa CAE.
 * 88 kart wzorcowych. Traktuj je jak szablon: każde nowe hasło rób w tym samym rytmie
 * (chunk + kolokacje + rejestr + pułapka), a nie jako gołe słowo z tłumaczeniem.
 */
window.CARDS = [

/* ========== LUKI W ZDANIU — kolokacje i wyrażenia (Use of English 1–2) ========== */

{ id: "cae_0001", t: "cloze", q: "The minister has ___ over his handling of the crisis.", a: "come under fire",
  pl: "spotkać się z ostrą krytyką", ipa: "/kʌm ˈʌndə ˈfaɪə/",
  coll: ["come under fire from critics", "come under heavy fire"],
  ex: ["The bill came under fire from both sides of the House."],
  reg: "neutralny, częsty w prasie", note: "Formalny odpowiednik: be subjected to criticism.", tags: ["polityka"] },

{ id: "cae_0002", t: "cloze", q: "Years of night shifts have ___ his health.", a: "taken their toll on",
  accept: ["taken a toll on", "taken a heavy toll on", "taken its toll on"],
  pl: "odbić się na czymś, zebrać żniwo",
  coll: ["take a heavy toll on", "the toll of the pandemic"],
  ex: ["The drought has taken its toll on this year's harvest."], reg: "neutralny" },

{ id: "cae_0003", t: "cloze", q: "Small businesses ___ the tax rise.", a: "bore the brunt of",
  accept: ["bear the brunt of"], pl: "ponieść najcięższe konsekwencje czegoś",
  coll: ["bear the brunt of the criticism", "bear the brunt of the costs"],
  ex: ["Coastal towns bore the brunt of the storm."], reg: "neutralny do formalnego" },

{ id: "cae_0004", t: "cloze", q: "With a twelve-point lead, the result was ___.", a: "a foregone conclusion",
  pl: "przesądzony wynik", ipa: "/ˌfɔːɡɒn kənˈkluːʒən/",
  ex: ["The vote was widely seen as a foregone conclusion."], reg: "neutralny" },

{ id: "cae_0005", t: "cloze", q: "His account of events is ___ the official version.", a: "at odds with",
  pl: "sprzeczny z czymś, w konflikcie z czymś",
  coll: ["be at odds with the evidence", "put somebody at odds with"],
  ex: ["The two reports are fundamentally at odds with each other."], reg: "neutralny do formalnego" },

{ id: "cae_0006", t: "cloze", q: "___ the scandal, three directors resigned.", a: "In the wake of",
  pl: "w następstwie czegoś",
  ex: ["Security was tightened in the wake of the attacks."],
  reg: "formalny", note: "Zawsze o skutkach wydarzenia, nie o zwykłej kolejności w czasie." },

{ id: "cae_0007", t: "cloze", q: "The results ___ what analysts had predicted.", a: "fell short of",
  accept: ["fall short of"], pl: "nie sprostać czemuś, wypaść poniżej",
  coll: ["fall short of expectations", "fall well short of the target"],
  ex: ["Revenues fell well short of the forecast."], reg: "neutralny" },

{ id: "cae_0008", t: "cloze", q: "The injury ___ his hopes of competing.", a: "put paid to",
  pl: "przekreślić coś, położyć czemuś kres",
  ex: ["The recession put paid to any thought of expansion."],
  reg: "brytyjski, nieco potoczny", note: "Zawsze o planach lub nadziejach, nie o rzeczach materialnych." },

{ id: "cae_0009", t: "cloze", q: "Open-plan offices are not always ___ concentration.", a: "conducive to",
  pl: "sprzyjający czemuś", ipa: "/kənˈdjuːsɪv/",
  coll: ["conducive to learning", "an atmosphere conducive to growth"],
  ex: ["The noise was hardly conducive to a good night's sleep."],
  reg: "formalny", note: "Zawsze z przyimkiem to, nigdy for." },

{ id: "cae_0010", t: "cloze", q: "Your previous convictions may ___ the sentence.", a: "have a bearing on",
  pl: "mieć wpływ na coś, mieć związek z czymś",
  coll: ["have a direct bearing on", "have little bearing on"],
  ex: ["Her age has no bearing on her ability to do the job."], reg: "formalny" },

{ id: "cae_0011", t: "cloze", q: "She ___ to conceal her identity.", a: "went to great lengths",
  accept: ["went to considerable lengths"], pl: "zadać sobie wiele trudu",
  ex: ["They went to great lengths to make us feel welcome."], reg: "neutralny" },

{ id: "cae_0012", t: "cloze", q: "A merger has been ___ for months.", a: "on the cards",
  pl: "prawdopodobny, wisi w powietrzu",
  ex: ["Promotion seems to be on the cards for her."],
  reg: "brytyjski, potoczny", note: "Amerykański wariant: in the cards." },

{ id: "cae_0013", t: "cloze", q: "I'd take those projections ___.", a: "with a pinch of salt",
  accept: ["with a grain of salt"], pl: "z przymrużeniem oka, z rezerwą",
  ex: ["His version of events should be taken with a pinch of salt."],
  reg: "brytyjski, potoczny", note: "Amerykański wariant: with a grain of salt." },

{ id: "cae_0014", t: "cloze", q: "The outcome is ___ certain at this stage.", a: "by no means",
  pl: "bynajmniej nie, wcale nie",
  ex: ["This is by no means the end of the matter."],
  reg: "formalny", note: "Na początku zdania wymusza inwersję: By no means is this over." },

{ id: "cae_0015", t: "cloze", q: "She told him ___ what she thought of the plan.", a: "in no uncertain terms",
  pl: "bez ogródek, dobitnie",
  ex: ["The court made its position clear in no uncertain terms."], reg: "formalny" },

{ id: "cae_0016", t: "cloze", q: "It took him months to ___ the new accounting system.", a: "get to grips with",
  accept: ["come to grips with"], pl: "opanować coś, uporać się z czymś",
  ex: ["We need to get to grips with the underlying problem."],
  reg: "brytyjski, neutralny", note: "Amerykański wariant: come to grips with." },

{ id: "cae_0017", t: "cloze", q: "Losing that contract turned out to be ___.", a: "a blessing in disguise",
  pl: "szczęście w nieszczęściu",
  ex: ["Missing the flight was a blessing in disguise."], reg: "neutralny" },

{ id: "cae_0018", t: "cloze", q: "That theory no longer ___ among economists.", a: "holds sway",
  pl: "dominować, mieć posłuch", ipa: "/həʊldz sweɪ/",
  coll: ["hold sway over somebody"],
  ex: ["For decades, that doctrine held sway over policy."], reg: "formalny, literacki" },

{ id: "cae_0019", t: "cloze", q: "The report ___ negligence and deliberate fraud.", a: "draws a distinction between",
  accept: ["draws a clear distinction between"], pl: "wprowadzać rozróżnienie między",
  coll: ["draw a sharp distinction", "blur the distinction"],
  ex: ["It is important to draw a distinction between the two cases."], reg: "formalny" },

{ id: "cae_0020", t: "cloze", q: "By delaying, you ___ losing the deal altogether.", a: "run the risk of",
  pl: "narażać się na ryzyko czegoś",
  ex: ["You run the risk of being misunderstood."],
  reg: "neutralny", note: "Zawsze z formą -ing po of." },

{ id: "cae_0021", t: "cloze", q: "Exports ___ nearly half of the company's revenue.", a: "account for",
  pl: "stanowić, odpowiadać za",
  coll: ["account for the majority of", "account for the discrepancy"],
  ex: ["Renewables now account for a third of output."],
  reg: "neutralny", note: "Drugie znaczenie: wyjaśniać. That accounts for the delay." },

{ id: "cae_0022", t: "cloze", q: "The decision ___ considerable controversy.", a: "gave rise to",
  accept: ["give rise to"], pl: "wywołać coś, dać początek czemuś",
  coll: ["give rise to speculation", "give rise to concern"],
  ex: ["The findings gave rise to a series of new studies."], reg: "formalny" },

{ id: "cae_0023", t: "cloze", q: "Refusing to answer would be ___ an admission of guilt.", a: "tantamount to",
  pl: "równoznaczny z czymś", ipa: "/ˈtæntəmaʊnt/",
  ex: ["The remark was tantamount to a declaration of war."],
  reg: "formalny", note: "Zawsze o czymś negatywnym lub poważnym w skutkach." },

{ id: "cae_0024", t: "cloze", q: "Given the uncertainty, we decided to ___.", a: "err on the side of caution",
  pl: "dmuchać na zimne, wybrać ostrożniejszy wariant", ipa: "/ɜː/",
  ex: ["I'd rather err on the side of caution and book two rooms."],
  reg: "neutralny do formalnego", note: "Czasownik err wymawia się /ɜː/, nie /eə/." },

{ id: "cae_0025", t: "cloze", q: "Last year's restructuring is ___.", a: "a case in point",
  pl: "dobry przykład na to, o czym mowa",
  ex: ["Many industries are struggling; shipbuilding is a case in point."], reg: "formalny" },

{ id: "cae_0026", t: "cloze", q: "The committee ___ the proposal after a brief discussion.", a: "did away with",
  accept: ["dispensed with"], pl: "znieść coś, pozbyć się czegoś",
  ex: ["The new rules did away with the paperwork entirely."], reg: "neutralny" },

{ id: "cae_0027", t: "cloze", q: "It ___ that the witness had been paid.", a: "later emerged",
  accept: ["subsequently emerged", "emerged"], pl: "wyszło na jaw",
  ex: ["It emerged that the data had been incomplete all along."],
  reg: "formalny, prasowy", note: "Konstrukcja bezosobowa: It emerged that…" },

{ id: "cae_0028", t: "cloze", q: "The two accounts are difficult to ___.", a: "reconcile",
  pl: "pogodzić ze sobą", ipa: "/ˈrekənsaɪl/",
  coll: ["reconcile A with B", "irreconcilable differences"],
  ex: ["How do you reconcile ambition with family life?"], reg: "formalny" },

/* ========== PRZYIMKI ZALEŻNE (Use of English 2) ========== */

{ id: "cae_0029", t: "prep", q: "The outcome depends largely ___ the weather.", a: "on",
  pl: "zależeć od", note: "Ale: It depends whether… bez przyimka przed spójnikiem." },
{ id: "cae_0030", t: "prep", q: "She is perfectly capable ___ handling it herself.", a: "of",
  pl: "zdolny do czegoś", note: "Po of zawsze forma -ing." },
{ id: "cae_0031", t: "prep", q: "The work was carried out in accordance ___ the regulations.", a: "with",
  pl: "zgodnie z", reg: "formalny, urzędowy" },
{ id: "cae_0032", t: "prep", q: "Growth was achieved at the expense ___ quality.", a: "of",
  pl: "kosztem czegoś" },
{ id: "cae_0033", t: "prep", q: "He was dismissed on the grounds ___ gross misconduct.", a: "of",
  pl: "z powodu, na podstawie", note: "Z rzeczownikiem: on the grounds of. Ze zdaniem: on the grounds that." },
{ id: "cae_0034", t: "prep", q: "In the light ___ recent events, the policy is under review.", a: "of",
  pl: "w świetle czegoś", note: "Brytyjskie in the light of, amerykańskie in light of." },
{ id: "cae_0035", t: "prep", q: "The offer is subject ___ approval by the board.", a: "to", pl: "podlegający czemuś" },
{ id: "cae_0036", t: "prep", q: "Children are particularly prone ___ ear infections.", a: "to",
  pl: "podatny na", note: "Zawsze o czymś niepożądanym." },
{ id: "cae_0037", t: "prep", q: "She is averse ___ taking unnecessary risks.", a: "to",
  pl: "niechętny czemuś", note: "Częściej w przeczeniu: not averse to a glass of wine." },
{ id: "cae_0038", t: "prep", q: "There is no substitute ___ experience.", a: "for", pl: "namiastka czegoś" },
{ id: "cae_0039", t: "prep", q: "He was oblivious ___ the tension in the room.", a: "to",
  accept: ["of"], pl: "nieświadomy czegoś", note: "oblivious to jest dziś częstsze niż oblivious of." },
{ id: "cae_0040", t: "prep", q: "The findings are consistent ___ earlier studies.", a: "with", pl: "zgodny z" },
{ id: "cae_0041", t: "prep", q: "The company is liable ___ any damage caused.", a: "for",
  pl: "odpowiedzialny za", note: "Ale: liable to a fine — narażony na coś." },
{ id: "cae_0042", t: "prep", q: "Access is restricted ___ authorised personnel.", a: "to", pl: "ograniczony do" },
{ id: "cae_0043", t: "prep", q: "The delay was attributed ___ a technical fault.", a: "to", pl: "przypisany czemuś" },
{ id: "cae_0044", t: "prep", q: "Nothing can compensate ___ the loss of a whole season.", a: "for", pl: "zrekompensować coś" },

/* ========== SŁOWOTWÓRSTWO (Use of English 3) ========== */

{ id: "cae_0045", t: "wordform", q: "persuade", hint: "rzeczownik", a: "persuasion",
  pl: "perswazja, przekonywanie", ex: ["It took a good deal of persuasion to get him to agree."] },
{ id: "cae_0046", t: "wordform", q: "persuade", hint: "przymiotnik, forma przecząca", a: "unpersuasive",
  pl: "nieprzekonujący", note: "Rodzina: persuade / persuasion / persuasive / persuasively / unpersuasive." },
{ id: "cae_0047", t: "wordform", q: "maintain", hint: "rzeczownik", a: "maintenance",
  pl: "utrzymanie, konserwacja", note: "Uwaga na pisownię: maintain, ale mainten-ance." },
{ id: "cae_0048", t: "wordform", q: "analyse", hint: "rzeczownik", a: "analysis",
  pl: "analiza", note: "Liczba mnoga: analyses. Amerykańska pisownia czasownika: analyze." },
{ id: "cae_0049", t: "wordform", q: "sustain", hint: "rzeczownik od przymiotnika", a: "sustainability",
  pl: "zrównoważony charakter, trwałość", note: "Łańcuch: sustain → sustainable → sustainability." },
{ id: "cae_0050", t: "wordform", q: "decide", hint: "przymiotnik, forma przecząca", a: "indecisive",
  pl: "niezdecydowany", note: "Nie unde-. Prefiks negatywny to in-." },
{ id: "cae_0051", t: "wordform", q: "strong", hint: "czasownik", a: "strengthen", pl: "wzmocnić" },
{ id: "cae_0052", t: "wordform", q: "long", hint: "rzeczownik", a: "length", pl: "długość" },
{ id: "cae_0053", t: "wordform", q: "anxious", hint: "rzeczownik", a: "anxiety",
  pl: "niepokój, lęk", ipa: "/æŋˈzaɪəti/", note: "Wymowa rzeczownika różni się od przymiotnika /ˈæŋkʃəs/." },
{ id: "cae_0054", t: "wordform", q: "consider", hint: "przymiotnik znaczący „znaczny, spory”", a: "considerable",
  pl: "znaczny", note: "Pułapka egzaminacyjna: considerable = duży, considerate = taktowny, uważający na innych." },
{ id: "cae_0055", t: "wordform", q: "economy", hint: "przymiotnik znaczący „oszczędny”", a: "economical",
  pl: "oszczędny", note: "Pułapka: economic = gospodarczy, economical = oszczędny w użyciu." },
{ id: "cae_0056", t: "wordform", q: "history", hint: "przymiotnik znaczący „przełomowy, doniosły”", a: "historic",
  pl: "przełomowy", note: "Pułapka: historic = doniosły, historical = dotyczący historii." },
{ id: "cae_0057", t: "wordform", q: "sense", hint: "przymiotnik znaczący „rozsądny”", a: "sensible",
  pl: "rozsądny", note: "Pułapka: sensible = rozsądny, sensitive = wrażliwy." },
{ id: "cae_0058", t: "wordform", q: "memory", hint: "przymiotnik znaczący „zapadający w pamięć”", a: "memorable",
  pl: "pamiętny", note: "Nie mylić z memorial — pomnikowy, upamiętniający." },
{ id: "cae_0059", t: "wordform", q: "compete", hint: "rzeczownik oznaczający osobę", a: "competitor",
  pl: "konkurent", note: "Rodzina: compete / competition / competitor / competitive / competitively." },
{ id: "cae_0060", t: "wordform", q: "prove", hint: "rzeczownik", a: "proof",
  pl: "dowód", note: "Zmiana pisowni v → f." },
{ id: "cae_0061", t: "wordform", q: "respond", hint: "przymiotnik znaczący „szybko reagujący”", a: "responsive",
  pl: "reagujący, wrażliwy na bodźce", note: "Nie mylić z responsible — odpowiedzialny." },
{ id: "cae_0062", t: "wordform", q: "advantage", hint: "przymiotnik", a: "advantageous",
  pl: "korzystny", ipa: "/ˌædvənˈteɪdʒəs/" },
{ id: "cae_0063", t: "wordform", q: "signify", hint: "rzeczownik", a: "significance", pl: "znaczenie, waga" },
{ id: "cae_0064", t: "wordform", q: "likely", hint: "rzeczownik", a: "likelihood", pl: "prawdopodobieństwo" },
{ id: "cae_0065", t: "wordform", q: "apply", hint: "przymiotnik znaczący „mający zastosowanie”", a: "applicable",
  pl: "mający zastosowanie", note: "Częste w formularzach: if applicable." },
{ id: "cae_0066", t: "wordform", q: "rely", hint: "przymiotnik, forma przecząca", a: "unreliable", pl: "niesolidny, zawodny" },
{ id: "cae_0067", t: "wordform", q: "conclude", hint: "przymiotnik znaczący „rozstrzygający”", a: "conclusive",
  pl: "rozstrzygający", coll: ["conclusive evidence", "conclusive proof"] },
{ id: "cae_0068", t: "wordform", q: "wide", hint: "czasownik", a: "widen", pl: "poszerzyć" },

/* ========== TRANSFORMACJE (Use of English 4) ========== */

{ id: "cae_0069", t: "transform", q: "I regret not applying for that job.", hint: "WISH",
  q2: "I ___ for that job.", a: "wish I had applied",
  note: "Żal o przeszłość: wish + past perfect." },
{ id: "cae_0070", t: "transform", q: "As soon as we arrived, it started raining.", hint: "SOONER",
  q2: "No ___ it started raining.", a: "sooner had we arrived than",
  note: "No sooner wymusza inwersję i łączy się z than, nie z when." },
{ id: "cae_0071", t: "transform", q: "Someone is repairing my car at the moment.", hint: "HAVING",
  q2: "I ___ at the moment.", a: "am having my car repaired",
  note: "Strona sprawcza: have + dopełnienie + past participle." },
{ id: "cae_0072", t: "transform", q: "It's a pity you didn't tell me earlier.", hint: "ONLY",
  q2: "If ___ me earlier.", a: "only you had told", note: "If only + past perfect dla żalu o przeszłość." },
{ id: "cae_0073", t: "transform", q: "People say he was a brilliant negotiator.", hint: "HAVE",
  q2: "He is said ___ a brilliant negotiator.", a: "to have been",
  note: "Konstrukcja raportująca: be said + bezokolicznik perfect dla przeszłości." },
{ id: "cae_0074", t: "transform", q: "I'd prefer you not to smoke in here.", hint: "RATHER",
  q2: "I ___ in here.", a: "would rather you didn't smoke",
  note: "would rather + podmiot + past simple, gdy dotyczy innej osoby." },
{ id: "cae_0075", t: "transform", q: "You should have booked the tickets weeks ago.", hint: "TIME",
  q2: "It's ___ the tickets.", a: "high time you booked",
  note: "It's high time + past simple, mimo znaczenia teraźniejszego." },
{ id: "cae_0076", t: "transform", q: "The meeting was cancelled because the staff went on strike.", hint: "OWING",
  q2: "The meeting was cancelled ___ the staff went on strike.", a: "owing to the fact that",
  note: "owing to łączy się z rzeczownikiem, więc przed zdaniem trzeba wstawić the fact that." },
{ id: "cae_0077", t: "transform", q: "He had no idea what he was getting into.", hint: "LITTLE",
  q2: "___ what he was getting into.", a: "Little did he know",
  note: "Little na początku zdania wymusza inwersję." },
{ id: "cae_0078", t: "transform", q: "Nobody expected the proposal to be rejected.", hint: "CAME",
  q2: "The rejection of the proposal ___ everybody.", a: "came as a surprise to" },
{ id: "cae_0079", t: "transform", q: "I only realised my mistake when I got home.", hint: "UNTIL",
  q2: "Not ___ I realise my mistake.", a: "until I got home did",
  note: "Not until na początku zdania wymusza inwersję w części głównej." },
{ id: "cae_0080", t: "transform", q: "It doesn't matter how hard you try, he won't change.", hint: "MATTER",
  q2: "No ___ you try, he won't change.", a: "matter how hard" },

/* ========== ZWROTY DO WRITINGU I SPEAKINGU ========== */

{ id: "cae_0081", t: "phrase", q: "aczkolwiek, chociaż (jednym słowem, formalnie)", a: "albeit",
  ipa: "/ɔːlˈbiːɪt/", ex: ["He accepted the offer, albeit reluctantly."],
  reg: "formalny, pisany", note: "Po albeit nie stawia się podmiotu z czasownikiem — tylko przymiotnik, przysłówek lub fraza." },
{ id: "cae_0082", t: "phrase", q: "trzeba przyznać, że (jednym słowem)", a: "admittedly",
  ex: ["Admittedly, the evidence is far from complete."], reg: "formalny",
  note: "Świetne otwarcie akapitu z ustępstwem w eseju CAE." },
{ id: "cae_0083", t: "phrase", q: "analogicznie, z tego samego powodu", a: "by the same token",
  ex: ["By the same token, tighter rules would harm smaller firms."], reg: "formalny" },
{ id: "cae_0084", t: "phrase", q: "można by argumentować, że", a: "it could be argued that",
  ex: ["It could be argued that the policy has achieved the opposite."],
  reg: "formalny", note: "Bezpieczna asekuracja w eseju — nie przypisujesz sobie twierdzenia wprost." },
{ id: "cae_0085", t: "phrase", q: "w celu, z myślą o (formalnie, do proposalu)", a: "with a view to",
  ex: ["The scheme was launched with a view to cutting waste."],
  reg: "formalny", note: "Po to zawsze forma -ing, nie bezokolicznik." },
{ id: "cae_0086", t: "phrase", q: "wiązałoby się to z, pociągałoby za sobą", a: "this would entail",
  ex: ["This would entail a substantial increase in staffing."], reg: "formalny" },
{ id: "cae_0087", t: "phrase", q: "o ile, w zakresie w jakim", a: "insofar as",
  accept: ["in so far as"], ex: ["The plan is workable insofar as funding is secured."], reg: "formalny" },
{ id: "cae_0088", t: "phrase", q: "nie mówiąc już o", a: "let alone",
  ex: ["He can't afford a flat, let alone a house."],
  reg: "neutralny", note: "Zawsze po zdaniu przeczącym." },
{ id: "cae_0089", t: "phrase", q: "co gorsza", a: "to make matters worse",
  ex: ["To make matters worse, the funding was withdrawn."], reg: "neutralny" },
{ id: "cae_0090", t: "phrase", q: "tak czy inaczej, mimo wszystko (formalnie)", a: "be that as it may",
  ex: ["Be that as it may, the deadline stands."], reg: "formalny" },
{ id: "cae_0091", t: "phrase", q: "tak z głowy, bez sprawdzania (mówione)", a: "off the top of my head",
  ex: ["Off the top of my head, I'd say about thirty."],
  reg: "potoczny", note: "Do Speakingu — naturalny sposób kupienia sobie czasu." },
{ id: "cae_0092", t: "phrase", q: "przyjmuję ten argument, ale (mówione, w dyskusji)", a: "I take your point, but",
  ex: ["I take your point, but that assumes people will actually use it."],
  reg: "neutralny", note: "Do Speaking Part 3, gdzie ocenia się umiejętność negocjowania." },
{ id: "cae_0093", t: "phrase", q: "czyniąc to, tym samym (formalnie)", a: "in so doing",
  ex: ["She resigned and, in so doing, set a precedent."], reg: "formalny, pisany" },
{ id: "cae_0094", t: "phrase", q: "gorąco zalecałbym, aby", a: "I would strongly recommend that",
  ex: ["I would strongly recommend that the scheme be extended."],
  reg: "formalny", note: "Po recommend that stosuje się tryb łączący: that it be, not that it is." },

/* ========== KOLOKACJE ========== */

{ id: "cae_0095", t: "coll", q: "___ a decision / an effort / progress", a: "make",
  pl: "podjąć decyzję, podjąć wysiłek, zrobić postęp",
  note: "make = tworzyć coś nowego; do = wykonywać czynność." },
{ id: "cae_0096", t: "coll", q: "___ research / harm / business", a: "do", pl: "prowadzić badania, wyrządzać szkodę" },
{ id: "cae_0097", t: "coll", q: "___ a risk / responsibility / offence", a: "take", pl: "podjąć ryzyko, wziąć odpowiedzialność, obrazić się" },
{ id: "cae_0098", t: "coll", q: "___ doubt on somebody's account", a: "cast",
  pl: "podać w wątpliwość", ex: ["The report casts doubt on the official figures."] },
{ id: "cae_0099", t: "coll", q: "___ light on a problem", a: "shed",
  accept: ["throw"], pl: "rzucić światło na coś", ex: ["The study sheds light on how the virus spreads."] },
{ id: "cae_0100", t: "coll", q: "___ the way for further reform", a: "pave",
  pl: "utorować drogę czemuś", ex: ["The ruling paved the way for similar claims."] },
{ id: "cae_0101", t: "coll", q: "___ a blind eye to the problem", a: "turn",
  pl: "przymykać oko na coś", reg: "neutralny" },
{ id: "cae_0102", t: "coll", q: "___ attention to detail", a: "pay", pl: "zwracać uwagę na szczegóły" },
{ id: "cae_0103", t: "coll", q: "___ a conclusion / a comparison / a parallel", a: "draw", pl: "wyciągnąć wniosek, dokonać porównania" },
{ id: "cae_0104", t: "coll", q: "___ an exception to the rule", a: "make", pl: "zrobić wyjątek" },

/* ========== DEFINICJA → SŁOWO ========== */

{ id: "cae_0105", t: "def", q: "showing great attention to detail; very careful and precise", a: "meticulous",
  pl: "skrupulatny, drobiazgowy", ipa: "/məˈtɪkjələs/",
  coll: ["meticulous record-keeping", "meticulously planned"] },
{ id: "cae_0106", t: "def", q: "refusing to change your views or to agree about something", a: "intransigent",
  pl: "nieprzejednany", ipa: "/ɪnˈtrænzɪdʒənt/", reg: "formalny" },
{ id: "cae_0107", t: "def", q: "expressed clearly in a few words", a: "succinct",
  pl: "zwięzły", ipa: "/səkˈsɪŋkt/", note: "Bliskie: concise, terse. Terse bywa odbierane jako opryskliwe." },
{ id: "cae_0108", t: "def", q: "likely to change suddenly and unpredictably, often for the worse", a: "volatile",
  pl: "niestabilny, zmienny", ipa: "/ˈvɒlətaɪl/", coll: ["a volatile market", "a volatile temperament"] },
{ id: "cae_0109", t: "def", q: "the ability to recover quickly from difficulties", a: "resilience",
  pl: "odporność psychiczna, sprężystość", coll: ["build resilience", "economic resilience"] },
{ id: "cae_0110", t: "def", q: "so obvious that it does not need to be proved", a: "self-evident",
  pl: "oczywisty sam przez się", reg: "formalny" },
{ id: "cae_0111", t: "def", q: "happening as a minor or unintended result of something else", a: "incidental",
  pl: "uboczny, przypadkowy", coll: ["incidental expenses", "incidental to the main argument"] },
{ id: "cae_0112", t: "def", q: "using too many words; unnecessarily wordy", a: "verbose",
  pl: "rozwlekły", ipa: "/vɜːˈbəʊs/", reg: "formalny" }

];
